### ISSUE TITLE
Our team: text styling

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#297]
Not all titles are centered below the image. Title should be centered. 

Line-height is also inconsistent. 

![image](https://github.com/hlxsites/mammotome/assets/55035633/8e82da09-fcfe-4556-83eb-dbccc19cf654)

**Comment by Acidham** [comment]
Caused by Word document formatting:
1. changed Name Header from normal to bold 
2. add centered selector in word doc in the Columns block (see Screenshot below)
3. remove new line in "Vice President, Sales and Service" with a line break (Word: SHIFT+Enter)

Please let me know if this resolves the issue

<img width="759" alt="Screenshot 2023-06-20 at 09 08 04" src="https://github.com/hlxsites/mammotome/assets/17712121/a5be18d7-6e81-40cb-b755-b91fd506dcab">

**Comment by krizel4** [comment]
> Caused by Word document formatting:
> 
> 1. changed Name Header from normal to bold 
> 
> 2. add centered selector in word doc in the Columns block (see Screenshot below)
> 
> 3. remove new line in "Vice President, Sales and Service" with a line break (Word: SHIFT+Enter)
> 
> 
> 
> Please let me know if this resolves the issue
> 
> 
> 
> <img width="759" alt="Screenshot 2023-06-20 at 09 08 04" src="https://github.com/hlxsites/mammotome/assets/17712121/a5be18d7-6e81-40cb-b755-b91fd506dcab">
> 
> 

Looks great. Thanks.
