### ISSUE TITLE
Country Values and SFDC Integration Values

### ISSUE THREAD

**Issue by krizel4** [hlxsites/mammotome#436]
I created a marketo trigger that works with the form and I was able to generate a notification e-mail from Marketo. But in order for the leads to sync from Marketo to Salesforce, some of the labels are different from the values. Below is a list, but I'll send the csv file in slack.

![image](https://github.com/hlxsites/mammotome/assets/55035633/6a0d16e6-6d8f-48a5-ac3c-e9527d8880a8)

**Comment by jalagari** [comment]
United States is not visible and we are also maintaining order it was broken as Options have comma as value and we were using comma as delimiter

**Comment by jalagari** [comment]
Use Case - Supporting of comma in Dropdown
```
Bolivia, Plurinational State of
Congo, the Democratic Republic of the
Iran, Islamic Republic of
Korea, Democratic People's Republic of
Macedonia, the former Yugoslav Republic of
Moldova, Republic of
```

- Mammotome forms have a Country field and they have few country names which contain commas.
- In Excel, we use comma as delimiter due to which Bolivia and Plurinational State of are listed as separate options

**Approach #1**: Different Delimiter - Use different delimiter like $ or \n which doesn't conflict with expected values.
**Approach #2**:  Support URL -

- Anyway we are storing country details in separate excel sheet as its used in multiple forms.
- We can publish it and then use that endpoint in Excel -> Option field.

Approach #2 looks better from authoring pov its looks strange as he need to aware of URL.

**Comment by Pareesh** [comment]
Corrected Country Values and text
