### ISSUE TITLE
Top Navigation - follow up

### ISSUE THREAD

**Issue by smiroslav** [hlxsites/mammotome#45]
This is the follow-up for https://github.com/hlxsites/mammotome/issues/12.

PR comments given in [PR 30](https://github.com/hlxsites/mammotome/pull/30) should be incorporated in this task, including
- animations for navigation items in mobile and desktop view
- language switcher
- "Kontakt us" button
- consider using SVG for navigation icons instead of "FontAwesome"
- size and positioning of the logo in desktop view
- second levels in desktop view should open on-mouse-over
- double-check font-size, font-weight, line-weight, font-family 
- double-check the size of menu-item panels
- in header.css extract styles common for mobile and desktop view 
- try to eliminate max-width breakpoints and override where necessary in a min-width break-point
- ...

**Comment by solaris007** [comment]
@dzehnder can you take a look at this? some of the items you already did as part of #12

**Comment by dzehnder** [comment]
### Progress:
- [ ] animations for navigation items in mobile and desktop view
- [ ] language switcher
- [ ] "Kontakt us" button
- [ ] consider using SVG for navigation icons instead of "FontAwesome"
- [ ] size and positioning of the logo in desktop view
- [ ] second levels in desktop view should open on-mouse-over
- [ ] double-check font-size, font-weight, line-weight, font-family
- [ ] double-check the size of menu-item panels
- [ ] in header.css extract styles common for mobile and desktop view
- [ ] try to eliminate max-width breakpoints and override where necessary in a min-width break-point
