### ISSUE TITLE
PDF-Viewer Full Screen Doesn't Work on Mobile Safari

### ISSUE THREAD

**Issue by solaris007** [hlxsites/mammotome#491]
Open https://www.mammotome.com/us/en/products/catalog on Mobile (iOS/Safari was used), hit the full-screen button. 

Seems to affect Safari on Mobile only. Chrome on iOS works.

**Comment by solaris007** [comment]
@dzehnder please take a look

**Comment by dzehnder** [comment]
Looks like Safari on iOS does not have a Full Screen API:
- https://web.dev/fullscreen/
- https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#api.element.requestfullscreen
- https://caniuse.com/fullscreen

Also, for Chrome on iOS, it does not seem to work as expected. To exit the full screen, you scroll up. So there is no way to scroll back up in the document, otherwise you exit the full screen again.

I would propose to disable the full screen function in those cases, and adjust the iframe accordingly (e.g switching to an In-Line version instead). WDYT @solaris007
